### ISSUE TITLE
Drop usage of very old methods

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/geninventorynumber#11]
Hi,

It seems the plugin actually uses methods in core that should have been deprecated (some parts were) and are going to be removed in 9.2 (see https://github.com/glpi-project/glpi/pull/1901).

**Comment by cedric-anne** [comment]
Done in https://github.com/pluginsGLPI/geninventorynumber/commit/ad5c69bead18fcf15f54ab72878d28adffa6b4a7.
