### ISSUE TITLE
No setup page after installing

### ISSUE THREAD

**Issue by RobertDorn** [pluginsGLPI/geninventorynumber#23]
Hi,
i am using glpi 9.4+1.1
After installing and activating the inventory generator i can't see the setup page. (there is no link behind inventory number generation) When I open the page manually (/plugins/geninventorynumber/front/config.php) I can do the setup and everything is saved but it doesn't work at all...

**Comment by Joimeld** [comment]
Bonjour,
J'ai GLPI 9.3+1.3, j'ai essayé d'installer geninventorynumber pour la 1ère fois mais il n'y a pas de lien de créé.
C'est comme le message de Robert Dorn, mais pas la même version de GLPI. J'ai essayé de modifier le fichier setup.php sans succès.

**Comment by Pafzedog** [comment]
Hello,

same here with 9.4.3, no configuration page and no action to generate inventory number.
I made last modification proposed by @cedric-anne and went to /plugins/geninventorynumber/front/config.php to configure plugin. After that I can choose action to bulk generate inventory number.

**Comment by stonebuzz** [comment]
Hi @Pafzedog 
can you try this PR

https://github.com/pluginsGLPI/geninventorynumber/pull/24

Best regards
