### ISSUE TITLE
No configuration Page

### ISSUE THREAD

**Issue by jcervantes-sipecom** [pluginsGLPI/geninventorynumber#27]
In the Wiki said to access the configuration page go to  Setup > Plugins, but the plugin no has a configuration page, I just can Install and Enable but that is, nothing else, I tried to follow what here says but nothing happen:
https://github.com/pluginsGLPI/geninventorynumber/issues/23

My GLPI Version:
GLPI 9.4.3 Copyright (C) 2015-2019 Teclib' and contributors
FusionInventory 9.4+1.1 - Copyleft © 2010-2019 by FusionInventory Team

**Comment by jcervantes-sipecom** [comment]
I had to put in browser the following link to access directly:

https://[glpi-ip/glpi]/plugins/geninventorynumber/front/config.php

**Comment by jcervantes-sipecom** [comment]
But It doesn't work still, how can I get it work?

**Comment by jcervantes-sipecom** [comment]
Hi, any support for using this plugins?

**Comment by stonebuzz** [comment]
Hi @jcervantes-sipecom can you look into "tools" menu ?

Best regards

**Comment by jcervantes-sipecom** [comment]
Thank for your reply @stonebuzz , this is the screenshot:
![image](https://user-images.githubusercontent.com/56606032/70446936-e2f8cb00-1a6b-11ea-9436-2f9c4baffdb5.png)
But I don't see anything in Tools about GenInventoryNumber

**Comment by stonebuzz** [comment]
Hi @jcervantes-sipecom 
can you try this PR

https://github.com/pluginsGLPI/geninventorynumber/pull/24

Best regards

**Comment by jcervantes-sipecom** [comment]
Perfect! it worked now!:

![image](https://user-images.githubusercontent.com/56606032/70553667-997ead80-1b49-11ea-9c7e-dc951454c1c7.png)

![image](https://user-images.githubusercontent.com/56606032/70553698-aac7ba00-1b49-11ea-83be-d14ede30622e.png)

![image](https://user-images.githubusercontent.com/56606032/70553649-8c61be80-1b49-11ea-9766-15c1a46f340a.png)

In my lab, I get that this bug is since geninventory 2.3.0 until 2.4.0 because the plugin version's 2.2.0 work without any problem. 

I comment these lines as just as you help, and everything work:

![image](https://user-images.githubusercontent.com/56606032/70553977-34778780-1b4a-11ea-8234-78a76ac0ebaf.png)
