### ISSUE TITLE
Le plugin ne fonctionne pas - The plugin does not work

### ISSUE THREAD

**Issue by DG-Caille** [pluginsGLPI/geninventorynumber#32]
Bonjour,
Hello,

J'ai plusieurs soucis avec le plugin.
I have several problems with the plugin.

1 - Lorsque je crée un nouvel élément, il n'y a aucun numéro d'inventaire qui est généré.
1 - When I create a new item, no inventory number is generated

2 - Lorsque je veux générer ou regénérer un numéro d'inventaire il n'y a pas l'option correspondante dans le menu "action" (ex recherche "num" pour numéro d'inventaire) :
2 - When I want to generate or regenerate an inventory number, there is no corresponding option in the "action" menu (e.g. search "num" for inventory number):
![image](https://user-images.githubusercontent.com/70632089/91985393-7f22da80-ed3d-11ea-8de8-8f348d9eb441.png)

3 - Lorsque je change d'entité je n'ai plus aucun affichage : 
3 - When I change entities, I no longer have any displays : 
![image](https://user-images.githubusercontent.com/70632089/91985933-a37eb700-ed3d-11ea-8e0e-ebe6188c4407.png)

J'ai essayé de désinstaller et réinstaller le plugin mais aucun changement.
I tried to uninstall and reinstall the plugin but no change.

Ma configuration actuelle : 
My current configuration : 
![image](https://user-images.githubusercontent.com/70632089/91983668-0d4a9100-ed3d-11ea-9ff3-b644b8219b46.png)

![image](https://user-images.githubusercontent.com/70632089/91984009-22272480-ed3d-11ea-896c-93b79f3dffd4.png)

Par ailleurs est-il possible d'avoir un numéro d'inventaire global différent par entité?
Is it also possible to have a different global inventory number per entity?

Je suis sur le profil super-admin 
I am on the super-admin profile 
Version GLPI : **9.5.1**
Version geninventorynumber : **2.5.0**

**Comment by lorenzo33** [comment]
Bonjour,

>>>>3 - Lorsque je change d'entité je n'ai plus aucun affichage :
Je constate le même problème. Nous avons plusieurs entités et lorsque que je veux utiliser le plugin depuis une autre entité que l'entité racine, le paramétrage de l'onglet Configuration Générale ne s'affiche pas. 

>>>>Par ailleurs est-il possible d'avoir un numéro d'inventaire global différent par entité?
Je souhaiterais également avoir cette fonctionnalité.

Merci pour votre aide.

**Comment by cedric-anne** [comment]
> Having an entity based configuration may be a good idea. If you want to sponsor this feature development, feel free to [contact GLPI editor team](https://portal.glpi-network.com/contact-us).

In fact, a development has been initiated in #37. Need to be reviewed.
