### ISSUE TITLE
Marketplace dosent work after installing Update

### ISSUE THREAD

**Issue by ORSTG** [pluginsGLPI/geninventorynumber#53]
GLPI10.0 
geninventorynumber 2.6.0

after downloading the new release you cant open the Marketplace again it shows up a black screen

**Comment by cedric-anne** [comment]
Hi,

Have you something related to this in `files/_log/php-errors.log` ?

**Comment by ORSTG** [comment]
Hi,

PHP Fatal error:  Cannot redeclare plugin_init_geninventorynumber() (previously declared in /var/www/html/glpi/marketplace/geninventorynumber/setup.php:39) in /var/www/html/glpi/plugins/geninventorynumber-2.6.0/setup.php on line 39, referer: http://servername/glpi/front/central.php



this line should make the problems(setup.php line39)   global $PLUGIN_HOOKS, $CFG_GLPI, $GENINVENTORYNUMBER_TYPES;

**Comment by cedric-anne** [comment]
`/var/www/html/glpi/plugins/geninventorynumber-2.6.0/` directory should be removed, and you should juste upgrade from the marketplace.
