### ISSUE TITLE
Error entering/saving items configuration

### ISSUE THREAD

**Issue by indi022** [pluginsGLPI/geninventorynumber#63]
Hi! When entring and saving items configuration I get the error below in php-errors.log (one entry when entering configuration, one entry when saving), no sql-errors.log entries. GLPI 10.0.1, geninventorynumber 2.8.0.
Additional sympthom: one line in the category templates column has no title (I can read "Computers", "Monitors", etc but one of them has no title, just the mask input box).

Error entry in php-errors.log:
[2022-07-21 19:08:27] glpiphplog.WARNING:   *** PHP Warning (2): call_user_func() expects parameter 1 to be a valid callback, class 'PluginGenericobjectHeadset' not found in /var/www/html/glpi/marketplace/geninventorynumber/inc/configfield.class.php at line 138
  Backtrace :
  ...lace/geninventorynumber/inc/config.class.php:91 PluginGeninventorynumberConfigField::showForConfig()
  src/CommonGLPI.php:670                             PluginGeninventorynumberConfig::displayTabContentForItem()
  ajax/common.tabs.php:111                           CommonGLPI::displayStandardTab()

**Comment by cedric-anne** [comment]
Hi,

#63 should fix this issue.

It seems that you previously had a `Headset` object in genericobject that was configured to use inventory number generation. Either this item has been removed, either genericobject plugin has been deactivated.

**Comment by indi022** [comment]
> Hi,
> 
> #63 should fix this issue.
> 
> It seems that you previously had a `Headset` object in genericobject that was configured to use inventory number generation. Either this item has been removed, either genericobject plugin has been deactivated.

True, I had a Headset object, and yes #65 it fixes this issue. Thanks to all!
