### ISSUE TITLE
Inventory number not generated

### ISSUE THREAD

**Issue by miquelangeld** [pluginsGLPI/geninventorynumber#7]
Hi, I'm using the current glpi versión, when I importing computers from OCS with the inventory number plugin enabled i get a message "inventory number created" and the number counter in settings is increasing but the inventory number is not inserted un otherserial field.

**Comment by kabassanov** [comment]
Did anybody confirm this bug? I've just manually imported a computer through ocsinventory-ng and the otherserial was correctly generated...

**Comment by trasher** [comment]
I throw the same issue testing the plugin with next GLPi version (9.1).

**Comment by trasher** [comment]
Just for information, the bug exists only in curent master, latest stable release is not affected.
