### ISSUE TITLE
GLPI 10.5

### ISSUE THREAD

**Issue by gjoulin** [pluginsGLPI/geninventorynumber#72]
Bonjour, 

Le plugin n'apparait pas dans la liste des plugins malgré le dépôt dans le dossier et j'ai une erreur  :
Warning: plugin_version_geninventorynumber-develop method must be defined! in /home/clients/d7d52b7c895ab143bdda7fd0d069f7c9/web/assistance/src/Plugin.php on line 1601

Comment faire  ?

**Comment by cconard96** [comment]
Le dossier du plugin doit être nommé "geninventorynumber" et non "geninventorynumber-develop".
