### ISSUE TITLE
How does this plugin work?

### ISSUE THREAD

**Issue by jerry-ne** [pluginsGLPI/geninventorynumber#96]
Hi. Sorry for this, but how does this plugin works?
I am excepting generate for example 20 new monitors asset's ID line in simply few steps.
Download and enable your plugin.
I spend 30 minutes for searching in GLPI: where you can compose this feature. 
I search under your github profile (no docs folder), under Issues, under [plugins.glpi-project.org](https://plugins.glpi-project.org/#/plugin/geninventorynumber). Now I am think I have wrong plugin for what I am looking for.

Please add the documentation sections to github or doc file to plugin folder.

GLPI 10.0.16

**Comment by andreaspollak** [comment]
It's in **Tools -> Inventory number generation**
